{
 "title": "Endpoint requests",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages registered",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(\"MessageId\") AS \"Messages\" FROM message LIMIT 50 "
    }
   ]
  },
  {
   "title": "Users registered",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(user_id) AS \"Users\" FROM \"user\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Follower registrations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(\"FollowerId\") AS \"Follower registrations\" FROM follower LIMIT 50 "
    }
   ]
  },
  {
   "title": "\"Latest\" registered",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"Latest\" FROM metadata LIMIT 50 "
    }
   ]
  },
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Rate of HTTP requests received per endpoint",
   "type": "timeseries",
   "description": "The Y-axis in the graph for this query represents the rate of HTTP requests per second for each specified endpoint. Each point on the Y-axis corresponds to the average number of requests received per second for each endpoint during each $__rate_interval.",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(http_requests_received_total{endpoint=~\"api/latest|api/register|api/msgs/{username}|api/fllws/{username}\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of requests (last 24hrs)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total[24h]))\r\n"
    }
   ]
  },
  {
   "title": "Total count of errors per code over (last 24hrs)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by(code) (increase(http_requests_received_total{code=~\"4..|5..|3..\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Duration by Endpoint",
   "type": "timeseries",
   "description": "The graph shows the average request duration in miliseconds. Each data point on the graph corresponds to the average time it took for requests to the specified endpoints to be processed during each $__rate_interval within the selected time range.",
   "gridPos": { "h": 16, "w": 14, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(rate(http_request_duration_seconds_sum{endpoint=~\"api/latest|api/register|api/msgs/\\\\{username\\\\}|api/fllws/\\\\{username\\\\}\"}[$__rate_interval])\r\n/\r\nrate(http_request_duration_seconds_count{endpoint=~\"api/latest|api/register|api/msgs/\\\\{username\\\\}|api/fllws/\\\\{username\\\\}\"}[$__rate_interval]))\r\n",
     "legendFormat": "Endpoint: {{endpoint}}, Method: {{method}}, Status Code: {{code}}"
    }
   ]
  },
  {
   "title": "Top 10 Unhandled Exception Endpoints ",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 18 },
   "targets": [
    {
     "expr": "topk(10, sum by(method, endpoint) (max_over_time(http_request_duration_seconds_count{instance=\"csharp-minitwit:5000\", job=\"csharp-minitwit\", endpoint!=\"\", code=~\"5..|4..\"}[$__rate_interval])))",
     "legendFormat": "{{enpoint}}"
    }
   ]
  },
  {
   "title": "Top 10 Requested Endpoints (API)",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 26 },
   "targets": [
    {
     "expr": "topk(10, sum by(method, endpoint) (max_over_time(http_request_duration_seconds_count{endpoint=~\"api/latest|api/register|api/msgs/\\\\{username\\\\}|api/fllws/\\\\{username\\\\}\", instance=\"csharp-minitwit:5000\", job=\"csharp-minitwit\"}[$__rate_interval])))",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}